### ISSUE TITLE
Async importScripts() in SW is problematic

### ISSUE THREAD

**Issue by jeffposnick** [surma/rollup-plugin-loadz0r#3]
As per the SW spec, and summarized at https://github.com/w3c/ServiceWorker/issues/1319#issuecomment-393386106, calls to `importScripts()` are allowed either during the initial, synchronous, top-level SW execution or during the `install` event handler.

Chrome doesn't currently follow the spec and allows arbitrary, async `importScripts()`, but this is a [bug](https://github.com/w3c/ServiceWorker/issues/1319#issuecomment-393718799) that needs to be fixed.

Using this library could lead to folks to inadvertently calls `importScripts()` in a way that is meant to be disallowed, and (if they only test on Chrome) erroneously thinking that everything works fine because Chrome isn't throwing an exception.

**Comment by surma** [comment]
Hm...

Good that you file this. I’ll leave it like this for now as the only alternative would be `fetch()` + `eval()`, which is not CSP compliant. I’ll add a note to the README.

**Comment by surma** [comment]
On second thought, I’ll leave this open and think a bit more on what the right course of action is

**Comment by surma** [comment]
Fixed in 8cb54b7084e23e5ecd0c5855bc4294d56950cb9e by providing an option.
