### ISSUE TITLE
transformChunk hook used by plugin loadz0r is deprecated

### ISSUE THREAD

**Issue by kaheglar** [surma/rollup-plugin-loadz0r#39]
As of Rollup 1.*

`(!) loadz0r plugin: The transformChunk hook used by plugin loadz0r is deprecated. The renderChunk hook should be used instead.`

https://github.com/rollup/rollup/pull/2409

**Comment by kaheglar** [comment]
Just noticed that :)

**Comment by surma** [comment]
Published v0.6 :)
