### ISSUE TITLE
Incompatible with banner option

### ISSUE THREAD

**Issue by tivac** [surma/rollup-plugin-loadz0r#7]
We've got a rollup config that includes the following

```js
{
    output : {
        // ...
        banner : "/* eslint-disable */",
    },
}
```

and that combined with `rollup-plugin-loadz0r` leads to all our chunks looking like this

```js
define("./chunk.js", [], nt-disable */
```

Since this plugin doesn't support setting a banner due to assumptions it makes about the output it's probably worth checking the `outputOptions` and yelling if a `banner` is set like it does for non-`amd` output.

https://github.com/surma/rollup-plugin-loadz0r/blob/4878de2051da27d9cf5c60b44cd557b065ef05dd/index.js#L41-L43

**Comment by surma** [comment]
Ah! Good shout. I guess technically I should fix the injection code, but I can’t be bothered. I’ll follow your suggestion and just start yelling :3
