### ISSUE TITLE
publicPath option

### ISSUE THREAD

**Issue by Rich-Harris** [surma/rollup-plugin-loadz0r#9]
I'm [working](https://github.com/sveltejs/sapper/pull/379) on adding Rollup support to [Sapper](https://sapper.svelte.technology/). Since Firefox doesn't yet support `import()` (and IE11 never will), and until you can use modules in workers, the plan is to use loadz0r. 

There's a wrinkle: loadz0r loads modules like this...

```js
script.src = './chunk-xyz123.js'
```

...but that URL is resolved relative to the *page*, not the importer. So if you have your scripts in a folder, or you're on a page other than `/`, the request fails.

Webpack solves this with [`options.publicPath`](https://webpack.js.org/configuration/output/#output-publicpath). Rollup *could* do the same, but since it doesn't (normally) bundle a loader, perhaps it makes sense to implement that option here? In Sapper's case it would look like this:

```js
loadz0r({
  publicPath: 'client'
})
```

I'm not immediately sure what the most sensible approach is, but let me know if this is something you'd accept a PR for. Thanks!

**Comment by Rich-Harris** [comment]
(Oh, forgot to mention: I made a lil' repro: https://github.com/Rich-Harris/rollup-plugin-loadz0r-issue-repro)

**Comment by surma** [comment]
I think an option is the right way to go here. The only requirement I set for loadz0r is to not have path resolution logic in the loader. _Very_ happy to accept a PR, otherwise I’ll whip something up next week :)
